version: '3'

services:
  campus-mysql:
    image: mysql:5.7
    container_name: campus-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: oddfar_imaotai
      MYSQL_DATABASE: 'campus_imaotai'
    volumes:
      - ./mysql/data/:/var/lib/mysql/
      - ./mysql/conf/:/etc/mysql/conf.d/
      - ./mysql/logs:/logs
      - ./../sql:/docker-entrypoint-initdb.d/
    command: [
      'mysqld',
      '--innodb-buffer-pool-size=80M',
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci',
      '--default-time-zone=+8:00',
      '--lower-case-table-names=1'
    ]
    networks:
      - imaotai

  campus-redis:
    image: redis:6.2.12
    container_name: campus-redis
    restart: always
    volumes:
      - ./redis/conf:/redis/config
      - ./redis/data/:/redis/data/
    command: "redis-server /redis/config/redis.conf"
    networks:
      - imaotai

  campus-nginx:
    image: nginx:1.23.4
    container_name: campus-nginx
    restart: always
    ports:
      - 80:80
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./nginx/dist:/usr/share/nginx/dist
      - ./nginx/cert:/etc/nginx/cert
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/log:/var/log/nginx
    depends_on:
      - campus-server
    networks:
      - imaotai

  campus-server:
    image: campus/campus-imaotai:1.0.12
    container_name: campus-imaotai
    restart: always
    environment:
      TZ: Asia/Shanghai
      SERVER_PORT: 8160
      spring.config.additional-location: /home/campus/conf/application-prod.yml
    volumes:
      - ./server/conf:/home/campus/conf
    depends_on:
      - campus-mysql
      - campus-redis
    networks:
      - imaotai

networks:
  imaotai: